version: "3.8"
services:
  mongo:
    image: mongo:6.0.13-jammy
    restart: always
    ports:
      - "27017:27017"   
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/backend
    depends_on:
      - mongo

volumes:
  mongo-data:


services:
  mongo:
    image: mongo:6.0.13-jammy
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/backend
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "4200:80"   # Angular usually runs on 4200
    depends_on:
      - backend

volumes:
  mongo-data:
